### ISSUE TITLE
New dialog component 🎁

### ISSUE THREAD

**Issue by alexbassy** [KittyGiraudel/ama#124]
Hey Kitty! Hope you are doing well ✨

Some people on the internet have recommended against building one’s own dialog from scratch. But there is a new [dialog element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) on the block with a few new features out of the box.

Do you plan to write a post on this summarising the differences between the old and new, and how to roll your own dialog component? I'm sure many people like me are curious (and stubborn) and want to write their own while still keeping accessibility in mind.

Thanks! <3

**Comment by KittyGiraudel** [comment]
Hey Alex! Very nice to hear from you, I hope you’re doing well. 😊

Fortunately, I do not have to write such post because [Scott O’Hara already did](https://www.scottohara.me/blog/2019/03/05/open-dialog.html). This is basically as good as it gets in terms of breaking for the status quo around the `<dialog>` element. TL;DR: you _can_ start using it but it might be worth relying on a library àla [a11y-dialog](https://a11y-dialog.netlify.app/) for a little while longer. Back in April, I also [explained why one would want to use a lib over the native element](https://github.com/KittyGiraudel/a11y-dialog/issues/330#issuecomment-1087653720).

If you’re looking to learn more about building an accessible dialog script, I [wrote about it](https://www.smashingmagazine.com/2021/07/accessible-dialog-from-scratch/) for Smashing Magazine last year. Rob Levin also [did a good piece](https://css-tricks.com/dialog-components-roll-your-own/) about the pros and cons of rolling one’s own dialog implementation for CSS-Tricks.

I hope this helps! Don’t hesitate to ask if you have any other question. 💚

**Comment by alexbassy** [comment]
Amazing! Shame about the drawbacks outlined in your last response to a dialog question but grateful to see them plainly laid out there. Our designer (who rightly reviews all work before release) still uses Safari 14 which gives our team a real possibility of not completing work if it's not catering to older browsers. Seems the library is still the way to go for now 😅 

Thanks for the answer - very helpful!
